- name: cp kube-controller-manager bin file to /usr/local/bin
  copy:
    src: k8s-master/kube-controller-manager
    dest: /usr/local/bin/kube-controller-manager
    owner: root
    group: root
    mode: 0755

- name: cp kube-controller-manager.service to /etc/systemd/system
  template: 
    src: kube-controller-manager/kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    owner: root
    group: root
    mode: 0644
  notify: restart kube-controller-manager

#- name: daemon reload
#  command: systemctl daemon-reload

- name: start kube-controller-manager
  systemd: 
    name: kube-controller-manager
    state: started
    enabled: yes
    daemon_reload: yes


